name: Deploy to Hostinger

on:
  push:
    branches: [ main ]  # Change 'main' to your branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          cd frontend_personal_page
          npm install

      - name: Build for production
        run: |
          cd frontend_personal_page
          npm run build

      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 154.56.33.201
          username: u123419025@154.56.33.201
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          local-dir: ./frontend_personal_page/dist/
          server-dir: ./
