name: Deploy to Hostinger

on:
  push:
    branches: [ main ]  # Change 'main' to your branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          cd frontend_personal_page
          npm install

      - name: Build for production
        run: |
          cd frontend_personal_page
          npm run build

      - name: Deploy to Hostinger
        uses: easingthemes/ftp-publish-action@v1
        with:
          ftp-server: ${{ secrets.HOSTINGER_URL }} # Define este secreto en la configuración de tu repositorio
          ftp-username: ${{ secrets.HOSTINGER_USERNAME }} # Define este secreto en la configuración de tu repositorio
          ftp-password: ${{ secrets.HOSTINGER_PASSWORD }} # Define este secreto en la configuración de tu repositorio
          local-dir: dist # Directorio donde se encuentra el build de tu proyecto
          remote-dir: /public_html # Directorio remoto en Hostinger
